apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-data-volume-claim
spec:
  volumeName: admin-data-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
