apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql
      volumeMounts:
        - mountPath: "/root/mountdb"
          name: db-data-storage
      envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-secret
      resources: {}
  volumes:
    - name: db-data-storage
      persistentVolumeClaim:
        claimName: db-data-volume-claim
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
